#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    n = len(arr)
    pos=neg=zero=0
    for i in arr:
        if i > 0:
            pos = pos + 1
        elif i < 0:
            neg = neg + 1
        else:
            zero = zero + 1
    print(f"There are {pos} positive numbers, {neg} negative numbers, and {zero} zero in the array.")
    print(f"The proportions of occurrence are positive: {pos}/{n} = %.6f, negative: {neg}/{n} = %.6f, zero: {zero}/{n} = %.6f" % (pos/n, neg/n, zero/n))
    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
